#ifndef UPOWERBACKEND_GLOBAL_H
#define UPOWERBACKEND_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(UPOWERBACKEND_LIBRARY)
#  define UPOWERBACKENDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define UPOWERBACKENDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // UPOWERBACKEND_GLOBAL_H
